#!/usr/bin/env bash
# merge-to-dev.sh -- safe merge of a feature branch into dev with
# automatic ID alignment.
#
# Usage:
#   scripts/merge-to-dev.sh <source-branch> [target-branch]
#
# Default target: dev.
#
# Steps:
#   1. Snapshot: <target> -> <target>-backup (lightweight, fast revert)
#   2. Switch to <source-branch>
#   3. Run tools/renumber-for-merge.py --target <target>
#   4. If renumber produced changes, commit them on <source-branch>
#   5. Switch to <target>, merge --no-ff <source-branch>
#
# On any failure, exit non-zero. Rollback for step 5: 'git reset --hard
# <target>-backup' on the target branch.
#
# This wrapper is the canonical way to merge feature branches in DIA-
# tracked repos. Direct 'git merge' is intercepted by the
# pre-merge-commit hook (see tools/git-hooks/pre-merge-commit) when
# id collisions exist, so terminal users cannot bypass the alignment
# step accidentally.
set -euo pipefail

if [ $# -lt 1 ] || [ $# -gt 2 ]; then
    echo "usage: $0 <source-branch> [target-branch]" >&2
    exit 2
fi

SOURCE=$1
TARGET=${2:-dev}

REPO_ROOT=$(git rev-parse --show-toplevel)
cd "$REPO_ROOT"

if [ -n "$(git status --porcelain)" ]; then
    echo "ERROR: working tree is not clean. Commit or stash first." >&2
    exit 1
fi

if ! git rev-parse --verify "$SOURCE" >/dev/null 2>&1; then
    echo "ERROR: source branch '$SOURCE' does not exist." >&2
    exit 1
fi
if ! git rev-parse --verify "$TARGET" >/dev/null 2>&1; then
    echo "ERROR: target branch '$TARGET' does not exist." >&2
    exit 1
fi

RENUMBER=tools/renumber-for-merge.py
if [ ! -f "$RENUMBER" ]; then
    # Fall back to the installed copy under .git/hooks-data when the
    # tool was deployed via install-git-hooks.sh.
    if [ -f ".git/hooks-data/renumber-for-merge.py" ]; then
        RENUMBER=".git/hooks-data/renumber-for-merge.py"
    else
        echo "ERROR: $RENUMBER not found." >&2
        exit 1
    fi
fi

echo "[merge-to-dev] target=$TARGET source=$SOURCE"

# 1. Snapshot
BACKUP="${TARGET}-backup"
git branch -f "$BACKUP" "$TARGET"
echo "[merge-to-dev] snapshot $BACKUP"

# 2. Switch to source
git checkout -q "$SOURCE"

# 3. Renumber if needed
if ! python3 "$RENUMBER" --target "$TARGET" --check-only; then
    echo "[merge-to-dev] id collisions detected, renumbering source branch"
    python3 "$RENUMBER" --target "$TARGET" --source "$SOURCE"
    if [ -n "$(git status --porcelain)" ]; then
        git add -A
        git commit -qm "chore(renumber): align ids with $TARGET before merge

Auto-generated by merge-to-dev.sh.
Branch ids reordered after target branch advanced."
        echo "[merge-to-dev] renumber commit landed on $SOURCE"
    fi
else
    echo "[merge-to-dev] no id collisions, skipping renumber"
fi

# 4. Merge
git checkout -q "$TARGET"
git merge --no-ff -m "Merge branch '$SOURCE' into $TARGET" "$SOURCE"
echo "[merge-to-dev] merge complete"
echo "[merge-to-dev] rollback: git checkout $TARGET && git reset --hard $BACKUP"
